name: jmu_tools
description: A simple tool for JMUer, and a light version of OpenJMU.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  android_scheme_search: ^1.0.0
  cookie_jar: ^3.0.0
  dartx: ^0.7.1
  device_info_plus: ^1.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  equatable: ^2.0.0
  extended_image: ^4.1.0
  ff_annotation_route_library: ^2.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^5.0.0+4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  html: ^0.15.0
  intl: any
  json_annotation: ^4.0.0
  logging: ^1.0.1
  oktoast: ^3.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.0.1
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  photo_manager: ^1.1.6
  provider: ^5.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.3
  hive_generator: ^1.1.0
  json_serializable: ^4.1.1
  process_run: ^0.12.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/placeholders/
