name: jmu_tools
description: A simple tool for JMUer, and a light version of OpenJMU.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartx: ^0.7.1
  dio: ^4.0.0
  equatable: ^2.0.0
  extended_image: ^4.0.0
  ff_annotation_route_library: ^2.0.1
  flutter_svg: ^0.21.0-nullsafety.0
  intl: any
  logging: ^1.0.1
  oktoast: ^3.0.0
  permission_handler: ^6.1.1
  photo_manager: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/placeholders/
